name: Build with Unit Tests

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Pinned 1.0.0 version

    - uses: actions/checkout@v2.3.4
      with:
        ref: ${{ inputs.ref }}
    - name: Cache
      uses: actions/cache@v2.1.3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ github.workflow }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-${{ github.workflow }}
    - name: Build with Maven
      run: mvn clean test -fae -T 2 -B -V -DcloudBuild -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.wagon.httpconnectionManager.ttlSeconds=25
    - name: Archive build artifacts
      uses: actions/upload-artifact@v2.2.2
      if: always()
      with:
        name: Build debug files
        path: |
          **/target/rat.txt
          **/target/surefire-reports/*
    - name: Surefire Report
      # Pinned 1.0.5 version
      uses: ScaCap/action-surefire-report@ad808943e6bfbd2e6acba7c53fdb5c89534da533
      if: always()
      with:
        # GITHUB_TOKEN
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit: ${{ inputs.ref }}
