name: release-to-maven-central
on: workflow_dispatch
jobs:
  release-job:
    runs-on: self-hosted
    steps:
#     - name: Get tag name
#       id: get_tag_name
#       run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - uses: actions/checkout@v2
      with:
        ref: v0.19.0.21
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Set up Apache Maven Central
      uses: actions/setup-java@v1
      with: # running setup-java again overwrites the settings.xml
        java-version: 1.8
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
  
    - name: Uploading additional JSON to Maven Central
      run: mvn deploy:deploy-file -DgroupId=io.github.PranavNair0001 -DartifactId=google-cloud -Dversion=0.19.0.7 -Dfile=target/google-cloud-0.19.0.7.json -Durl=https://s01.oss.sonatype.org/service/local/staging/deploy/maven2 -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASSPHRASE }}

    - name: Publish to Apache Maven Central
      run:  mvn -DskipTests clean deploy -P release -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASSPHRASE }}
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
